# Configuration for Alacritty, the GPU enhanced terminal emulator.
# Comple documentation available at https://alacritty.org/config-alacritty.html

import = ["~/.config/alacritty/themes/dracula.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"

[scrolling]
history = 10000

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 0
y = 0
