#!/usr/bin/env bash

# Source fzf accodingly based on how it has been installed
if [ -f ~/.fzf.bash ]; then
    # Source install
    source ~/.fzf.bash
else
    # Installed through pkg manager
    for file in /usr/share/doc/fzf/examples/key-bindings.bash \
                /usr/share/doc/fzf/examples/completion.bash
    do
       [ -f ${file} ] && source ${file}
    done
fi
