#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Missing mandatory shell extension when sourcing this file"
    exit 1
fi

if command -v direnv >/dev/null 2>&1
then
    case "${1}" in
        "bash" | "zsh")
            eval "$(direnv hook ${1})"
            ;;
        "fish")
            direnv hook fish | source
            ;;
        *)
            echo "Unkonwn direnv hook pattern for shell ${1}"
            ;;
    esac
fi
