#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Missing mandatory shell extension when sourcing this file"
    exit 1
fi

if ! command -v fzf >/dev/null && [ -f ~/.fzf.${1} ]
then
    # Source local install
    source ~/.fzf.${1}
fi

if command -v fzf >/dev/null
then
    # When installed through pkg manager, key bindings needs to be added
    # manually
    for file in /usr/share/doc/fzf/examples/key-bindings.${1} \
                /usr/share/doc/fzf/examples/completion.${1}
    do
        [ -f ${file} ] && source ${file}
    done

    alias printenvf="printenv | fzf"
    alias psf="ps -aux | fzf"
fi
