(
 ("default" . ((user-emacs-directory . "~/.spacemacs")
               (env . (("SPACEMACSDIR" . "~/.config/spacemacs")))
               )
  )
 ("spacemacs" . ((user-emacs-directory . "~/.spacemacs")
                 (env . (("SPACEMACSDIR" . "~/.config/spacemacs")))
               )
  )
 ("doom" . ((user-emacs-directory . "~/.doomemacs")
            (env . (("DOOMDIR" . "~/.config/doomemacs")))
            )
  )
 )
